name = "immutable_lru"
version = "1.0.0"


description = "Immuable LRU cache"
licences = ["MIT"]
repository = { type = "github", user = "chrsnstdd", repo = "immutable_lru" }


[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
